name: Analyzer

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  analyzer:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
